name=ADF4157
version=1.0.0
author=Dawid Szymanski SQ6EMM
maintainer=Dawid Szymanski SQ6EMM
sentence=Library for the Analog Devices ADF4157 fractional-N PLL frequency synthesizer.
paragraph=Handles register calculation and SPI write to the chip. Based on ADF4351 code by JA Soler EA3HMJ and Bo OZ2M.
category=Signal Input/Output
url=https://github.com/sq6emm/adf4157
architectures=*
includes=ADF4157.h
depends=SPI
